[phases.setup]
nixPkgs = ["python3", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "expat", "libxcb", "libX11", "libXcomposite", "libXdamage", "libXext", "libXfixes", "libXrandr", "libgbm", "pango", "cairo", "alsa-lib"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]
